import { db } from "@/db/db"
import type { Exercise, ExerciseType } from "@/db/schema"
import { setFieldsForExerciseType } from "@/shared/model/setFields"

const routineCsvColumns = [
  "Exercise ID",
  "Weight",
  "Reps",
  "Distance",
  "Time",
]

function csvQuote(value: string) {
  return `"${value.replaceAll('"', '""')}"`
}

function sortByExerciseId(a: Exercise, b: Exercise) {
  return a.id.localeCompare(b.id)
}

function parameterLabelsForExerciseType(exerciseType: ExerciseType) {
  return setFieldsForExerciseType(exerciseType).map((field) => field.label)
}

function formatExerciseParameterRow(exercise: Exercise) {
  return [
    csvQuote(exercise.id),
    csvQuote(parameterLabelsForExerciseType(exercise.exerciseType).join(",")),
  ].join(",")
}

export async function buildTrainingLogShareInstructions() {
  const exercises = await db.exercises.toArray()
  const exerciseRows = exercises.sort(sortByExerciseId).map(
    formatExerciseParameterRow,
  )

  return [
    "Generated by Upraglog, a workout tracking app.",
    "",
    "Available exercise ids and set parameters:",
    ...exerciseRows,
    "",
    "Parameter value formats must match the attached spreadsheet export:",
    "Weight: plain number without unit text.",
    "Reps: plain number without unit text.",
    "Distance: plain number without unit text.",
    "Time: duration text formatted as m:ss or h:mm:ss, for example 0:45 or 1:05:00.",
    "",
    "If the user asks for a workout routine, answer with exactly one fenced code block containing a CSV table and no extra prose. The first column must be Exercise ID. Use this exact header:",
    routineCsvColumns.join(","),
    "Use only exercise ids from the list above. Leave cells empty when a parameter is null, N/A, or does not apply to that exercise.",
  ].join("\n")
}
